name: portfolio
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  file_picker: ^10.1.0
  url_strategy: ^0.3.0
  flutter_bloc: ^9.1.0
  dio: ^5.8.0+1
  get_it: ^8.0.3
  cached_network_image: ^3.4.1
  dio_web_adapter: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  very_good_analysis: ^7.0.0

flutter:
  # web:
  #   renderer: html
  uses-material-design: true

  assets:
    - assets/images/
    - assets/projects/
